[package]
name = "rust_init"
version = "0.1.0"
authors = ["Thales César <thalesgiriboni@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
